# This is a Kubernetes Deployment manifest
# This manifest creates a Deployment that manages a set of replicas of a Pod
# The Deployment ensures that the desired number of replicas are running at all times

---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello 
    spec:
      containers:
        - name: hello
          image: 977098995865.dkr.ecr.ap-south-1.amazonaws.com/dev/test:latest
          ports:
            - containerPort: 8080
